content_dir = "content"
source = "zola"

[defaults]
canonical_phrase = "Originally published on my website:"

[zola]
section_url_from_path = true

[mastodon]
max_chars = 500
template = """
{excerpt}

New post: {title} {url}
"""

[bluesky]
max_chars = 300
template = """
New post: {title}

{excerpt}
{url}"""

[reddit]
kind = "link"
subreddit = "/r/example"
title_template = "{title}"
comment_template = """
{excerpt}

Originally published here: {url}
"""

[markdown]
template = """
# {title}
_{description}_

{body}

{canonical_phrase} {url}
"""
